import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { z } from "zod";
import { analyzeTranscriptDeterministically } from "@/lib/detect";

const RecommendSchema = z.object({
  questions: z.array(z.string()).min(2),
  pauseMessage: z.string(),
  outOfBandAction: z.string(),
  escalationWarning: z.string(),
  reasoning: z.string(),
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const transcript = body?.transcript || "";
    const callerName = body?.callerName || "Unknown Caller";
    const callerNumber = body?.callerNumber || "";
    const scenarioCategory = body?.scenarioCategory || "";

    // Support API key from header, body, or server env
    const headerKey = req.headers.get("x-gemini-api-key")?.trim();
    const bodyKey = body?.apiKey?.trim();
    const envKey = process.env.GEMINI_API_KEY?.trim();
    const apiKey = headerKey || bodyKey || envKey;

    const modelName = process.env.GEMINI_MODEL?.trim() || "gemini-2.5-flash";

    if (apiKey && transcript) {
      try {
        const ai = new GoogleGenAI({ apiKey });
        const systemInstruction = `You are PauseCall's expert verification AI assistant for older adults.
The user is currently on an incoming call with an alleged entity: "${callerName}" (${callerNumber}).
Scenario context: "${scenarioCategory}".
Transcript of what the caller has said so far:
"""
${transcript}
"""

Your task is to recommend 2 to 3 targeted "Reverse-Challenge Questions" to give the user to read to the caller.
Guidelines:
1. Exploit the caller's specific claims and lack of verified biographical context (e.g. employee badge number, desk extension, supervisor name, local field office, bank branch location, last 2 digits of account, private family safe word).
2. The questions must be polite, procedural, dignified, and specific to what this caller just said.
3. Provide a calm, reassuring pause message (1 sentence).
4. Provide the safest out-of-band verification action (e.g. hang up and call the number on your physical card or official government directory).
5. Anticipate how the scammer will escalate or try to deflect with urgency or threats.
6. Provide a concise explanation of why these specific questions expose the caller's deception.

Return ONLY a valid JSON object matching this schema:
{
  "questions": [
    "Question 1 to ask the caller",
    "Question 2 to ask the caller",
    "Question 3 to ask the caller"
  ],
  "pauseMessage": "Calm, dignified reassurance that the user is in control and does not need to decide now.",
  "outOfBandAction": "Clear advice to hang up and verify through trusted official channels.",
  "escalationWarning": "What the scammer is likely to say when challenged.",
  "reasoning": "Why these specific questions disrupt this specific caller's script."
}`;

        const response = await ai.models.generateContent({
          model: modelName,
          contents: `Recommend verification questions based on what ${callerName} just said in this transcript.`,
          config: {
            systemInstruction,
            responseMimeType: "application/json"
          }
        });

        const rawText = response.text || "";
        const cleaned = rawText.replace(/^```(json)?\s*/i, "").replace(/\s*```$/i, "").trim();
        const parsed = JSON.parse(cleaned);
        const validated = RecommendSchema.parse(parsed);

        return NextResponse.json({
          ...validated,
          source: "gemini"
        });
      } catch (geminiError: any) {
        console.warn("[recommend-questions] Gemini API error, falling back to offline rules:", geminiError?.message || geminiError);
      }
    }

    // Deterministic fallback
    const offline = analyzeTranscriptDeterministically(transcript);
    return NextResponse.json({
      questions: offline.verification_questions,
      pauseMessage: offline.pause_message,
      outOfBandAction: offline.out_of_band_action,
      escalationWarning: offline.escalation_warning,
      reasoning: "Generated by PauseCall on-device heuristic engine based on intercepted linguistic cues.",
      source: "offline_rules"
    });
  } catch (err: unknown) {
    console.error("[recommend-questions] Server error:", err);
    return NextResponse.json(
      { error: "Failed to generate question recommendations." },
      { status: 500 }
    );
  }
}
